### ISSUE TITLE
:recycle: Implement EIP 4626 - Token Vault Standard :rocket: 

### ISSUE THREAD

**Issue by refcell** [refcell/cairomate#25]
Implement a token vault standard based off of [EIP 4626](https://eips.ethereum.org/EIPS/eip-4626).

**Comment by milancermak** [comment]
I wanted to give this a go, I have some of it already done for a project I'm working on. However, since we don't have inheritance in Cairo plus there's, as of yet, no `mint` functionality in cairomate's ERC20 implementation, there's no straightforward way how to add it to the repo.

Do you have any opinion on how this module should be incorporated?
